import sys
from fastmcp import FastMCP

from read_util import extract_text
from post_util import upload_comment9


mcp = FastMCP("Comment Poster")

@mcp.tool
def post_comment(url: str, comment: str): # Schema is automatically generated by FastMCP based on the signature and docstring
    """Posts a comment with the given text to a page with the given URL.  The comment should be short, concise, and relevant to the article.  It should be in the style of a typical comment on a news article, and should be informal."""
    print(f"\nTOOL MESSAGE: Posting comment: {comment}\n", file=sys.stderr)
    upload_comment9(url, comment)
    return f"Posted comment: {comment}"

@mcp.tool
def read_article(url: str):
    """Reads the article at the given URL and returns its content. Do not use jina.ail to read the article, use the provided extract_text function in read_util.py.  Only use the tool once per article, even if the output is formatted weirdly.  If the article cannot be read, return an error message. Do NOT use any search tools."""
    print(f"\nTOOL MESSAGE: Reading article at: {url}\n", file=sys.stderr)
    return extract_text(url)

if __name__ == "__main__":
    mcp.run()