import sys
from fastmcp import FastMCP


mcp = FastMCP("Comment Poster")

@mcp.tool
def post_comment(comment: str): # Schema is automatically generated by FastMCP based on the signature and docstring
    """Posts a comment with the given text.  Comments should be concise, relevant, and three sentences."""
    print(f"Posting comment: {comment}", file=sys.stderr)
    return f"Posted comment: {comment}"

if __name__ == "__main__":
    mcp.run()